// <auto-generated />
namespace KitaplarEntityCodeFirst.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class deleteD_TarihiDetayColumnInYazarsTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(deleteD_TarihiDetayColumnInYazarsTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202211250704305_deleteD_TarihiDetayColumnInYazarsTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
